baseURL = 'https://idklaws.github.io/CourtNote-China/'
languageCode = 'zh-cn'
title = '庭记'
theme = 'hugo-PaperMod'


# 推荐添加的配置
relativeURLs = false
canonifyURLs = false

# 其他基本信息
 copyright = "© 2025 庭记. All Rights Reserved."
 enableRobotsTXT = true # 允许搜索引擎抓取


 [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "简介"
    url = "/courtnote/" # 对应你创建的目录
    weight = 2

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3

#[[menu.main]]
#   name = "协议"
#  url = "/terms/"
# weight = 4

[[menu.main]]
    name = "隐私"
    url = "/privacy/"
    weight = 4


[params]
    description = "庭记的官方网站，展示我们最新的创新产品和解决方案。" # 网站的整体描述
    keywords = ["庭记", "诉讼律师工具","开庭日程管理", "笔录照片转PDF", "技术","扫描", "创新"] # 网站的关键词

    # [params.homeInfoParams]
    #    # 首页顶部信息，可以写产品口号或简介
    #     Title = "庭记 — 法律人的日程与扫描助手"
    #   Content = "专业扫描生成高质量 PDF，开庭日程提醒与案号自动填写，一站式提升办案效率。文档本地保存，iCloud 仅同步日程，无广告与追踪。iOS 17+。"